### PR TITLE
Simplifying the README

### PR DESCRIPTION
**Pull request by emedvedev**
Made a few README changes, mostly to reflect a new token generation procedure (it’s really simple now, you’re getting a token in the Yammer’s web interface) and fix a few typos. Please review and I’ll merge after your LGTM. :)

@athieriot: btw, gave you a shoutout at https://stackstorm.com/2016/02/08/stackstorm-yammer-cat-pictures/ :)

### CODE REVIEW

**Comment by athieriot** [comment]
Awesome ! Thank you for that :)

And your product seems pretty amazing. Not sure I've see Bots used for support anywhere before.

P.S: LGTM

**Comment by emedvedev** [comment]
LGTM

**Comment by emedvedev** [comment]
Looks like we have to LGTM ourselves, too. Funny :)

**Comment by athieriot** [comment]
Yeah it needs two people so... :)

**Pull request merged**
