### PR TITLE
Cleanup

### PR DESCRIPTION
**Pull request by emedvedev**
Minor cleanup and refactoring, mainly replacing `console.log` with Hubot's `robot.logger`. Adapter's logs now behave as native Hubot's logs would: timestamped, categorized and controlled by logging settings. Fixed some slight spacing and formatting issues, too.

I'll test this PR some more before merging.

@athieriot: I bumped the version to 0.2.1, but nothing really changed except for logging, so there's no rush with publishing, don't worry!

### CODE REVIEW

**Comment by athieriot** [comment]
No worries, nudge me when you want it.

I took the liberty to plug ```lgtm.co``` on the project.
More details here: https://lgtm.co/docs/overview/ but basically it requires 2 maintainers (Well, us too at the moment which is a bit weird but hey !) to approve the PR before it can be merged. 
Approval is made through a comment stating "LGTM".

**Comment by emedvedev** [comment]
Perfect! I'll nudge you when I finish testing the branch.

**Comment by emedvedev** [comment]
LGTM

**Comment by emedvedev** [comment]
Nice, LGTM and Travis is a good setup. We'll have to write some tests later :) The PR should be fine to merge now.

**Pull request merged**
